input {
  file {
    path => "/app/log/log_error.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => multiline {
      pattern => "^(\d{2}-\d{2}-\d{2}\.\d{2}:\d{2}:\d{2}\.\d{3}|\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3})"
      negate => true
      what => "previous"
      auto_flush_interval => 2
    }
  }
}

filter {
  mutate {
    add_field => {
      "serviceName" => "order-service"
      "application" => "order-service"
      "app" => "order-service"
      "logSource" => "local-file"
    }
  }

  grok {
    match => {
      "message" => [
        "%{TIMESTAMP_ISO8601:log_time}\s+%{LOGLEVEL:level}\s+%{NUMBER:pid:int}\s+---\s+\[%{DATA:application_thread}\]\s+\[%{DATA:thread}\]\s+%{DATA:logger}\s+:\s+%{GREEDYDATA:log_message}",
        "%{DATA:log_time} \[%{DATA:thread}\] %{LOGLEVEL:level}\s+%{DATA:logger}\s+%{GREEDYDATA:log_message}"
      ]
    }
    tag_on_failure => ["ops_log_grok_failed"]
  }

  date {
    match => ["log_time", "ISO8601", "yy-MM-dd.HH:mm:ss.SSS"]
    timezone => "Asia/Shanghai"
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ops-demo-service-log-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}

