input {
  file {
    path => "/app/log/log_error.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb-ops-error.log"
    codec => multiline {
      pattern => "^\d{2}-\d{2}-\d{2}\.\d{2}:\d{2}:\d{2}\.\d{3}"
      negate => true
      what => "previous"
      auto_flush_interval => 2
    }
  }
}

filter {
  mutate {
    add_field => {
      "serviceName" => "ops-demo-service"
      "application" => "ops-demo-service"
      "app" => "ops-demo-service"
      "logSource" => "local-file"
    }
  }

  grok {
    match => {
      "message" => "%{DATA:log_time} \[%{DATA:thread}\] %{LOGLEVEL:level}\s+%{DATA:logger}\s+%{GREEDYDATA:log_message}"
    }
    tag_on_failure => ["ops_log_grok_failed"]
  }

  date {
    match => ["log_time", "yy-MM-dd.HH:mm:ss.SSS"]
    timezone => "Asia/Shanghai"
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ops-demo-service-log-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}

