package com.opsautoagent.domain.ops.service.execute;

import com.opsautoagent.domain.ops.adapter.repository.IOpsAgentRepository;
import com.opsautoagent.domain.ops.agent.governance.OpsToolGovernanceDecision;
import com.opsautoagent.domain.ops.agent.evidence.OpsEvidenceSignalExtractor;
import com.opsautoagent.domain.ops.agent.plan.OpsInvestigationPlan;
import com.opsautoagent.domain.ops.agent.review.OpsAgentReview;
import com.opsautoagent.domain.ops.agent.review.OpsEvidenceReviewResult;
import com.opsautoagent.domain.ops.agent.review.OpsEvidenceReviewerService;
import com.opsautoagent.domain.ops.agent.state.OpsAgentStateService;
import com.opsautoagent.domain.ops.model.entity.EvidenceItemEntity;
import com.opsautoagent.domain.ops.model.entity.EvidenceSemanticEntity;
import com.opsautoagent.domain.ops.model.entity.EvidenceSignalEntity;
import com.opsautoagent.domain.ops.model.entity.IncidentCommandEntity;
import com.opsautoagent.domain.ops.model.entity.LogEvidenceEntity;
import com.opsautoagent.domain.ops.model.entity.MetricEvidenceEntity;
import com.opsautoagent.domain.ops.model.entity.OpsAnalyzeEventEntity;
import com.opsautoagent.domain.ops.model.entity.RootCauseCandidateEntity;
import com.opsautoagent.domain.ops.model.entity.RunbookMatchEntity;
import com.opsautoagent.domain.ops.model.entity.TraceEvidenceEntity;
import com.opsautoagent.domain.common.tree.StrategyHandler;
import com.alibaba.fastjson.JSON;
import jakarta.annotation.Resource;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Slf4j
@Service
public class OpsStep5EvidenceCorrelationNode extends AbstractOpsAgentExecuteSupport {

    @Resource
    private OpsStep6RootCauseAnalysisNode opsStep6RootCauseAnalysisNode;

    @Resource
    private OpsEvidenceReviewerService evidenceReviewerService;

    @Resource
    private OpsEvidenceSignalExtractor evidenceSignalExtractor;

    @Resource
    private OpsAgentStateService opsAgentStateService;

    @Resource
    private IOpsAgentRepository opsAgentRepository;

    @Value("${ops.agent.max-rounds:2}")
    private int maxRounds;

    @Override
    protected String doApply(IncidentCommandEntity requestParameter,
                             DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext) throws Exception {
        List<EvidenceSignalEntity> evidenceSignals = evidenceSignalExtractor.extract(
                requestParameter,
                dynamicContext.getMetricEvidence(),
                dynamicContext.getLogEvidence(),
                dynamicContext.getTraceEvidence());
        dynamicContext.setEvidenceSignals(evidenceSignals);
        workingMemoryService.refreshFromContext(requestParameter, dynamicContext);
        send(dynamicContext, OpsAnalyzeEventEntity.running("analysis", "evidence_signals", 5,
                formatEvidenceSignals(evidenceSignals), requestParameter.getSessionId()));

        List<RunbookMatchEntity> runbookMatches = collectRunbookPatterns(requestParameter, dynamicContext, evidenceSignals,
                "retrieve Runbook patterns from neutral evidence signals");
        dynamicContext.setRunbookMatches(runbookMatches);
        dynamicContext.setRootCauseCandidates(List.of());
        workingMemoryService.refreshFromContext(requestParameter, dynamicContext);
        send(dynamicContext, OpsAnalyzeEventEntity.running("analysis", "evidence_chain", 5,
                "Root-cause candidates are not pre-generated by rules. Evidence Reviewer Agent will decide from neutral evidence signals and Runbook/RAG context.",
                requestParameter.getSessionId()));
        OpsEvidenceReviewResult reviewResult = reviewAndPersist(requestParameter, dynamicContext, 1, "REVIEWING");

        if (needsSupplement(reviewResult)) {
            int supplementRound = Math.min(Math.max(2, reviewResult.getRound() + 1), Math.max(1, maxRounds));
            send(dynamicContext, OpsAnalyzeEventEntity.running("agent", "evidence_reviewer_agent", 5,
                    buildReviewMessage(reviewResult) + "\nReviewer requested supplemental evidence. Starting round " + supplementRound + ".",
                    requestParameter.getSessionId()));
            opsAgentStateService.updateReviewSnapshot(
                    requestParameter.getDiagnosisId(),
                    reviewResult.getRound(),
                    JSON.toJSONString(dynamicContext.getMetricEvidence()),
                    JSON.toJSONString(dynamicContext.getLogEvidence()),
                    JSON.toJSONString(dynamicContext.getTraceEvidence()),
                    JSON.toJSONString(dynamicContext.getRootCauseCandidates()),
                    JSON.toJSONString(reviewResult),
                    reviewResult.getStatus(),
                    "NEED_MORE_EVIDENCE");
            OpsInvestigationPlan supplementalPlan = planExecutionService.createSupplementalPlan(
                    requestParameter,
                    dynamicContext,
                    reviewResult,
                    supplementRound,
                    Math.max(1, maxRounds));
            if (supplementalPlan == null) {
                planExecutionService.addSupplementalTools(dynamicContext, reviewResult.getRequiredTools());
            }
            opsAgentStateService.updateReviewSnapshot(
                    requestParameter.getDiagnosisId(),
                    supplementRound,
                    JSON.toJSONString(dynamicContext.getMetricEvidence()),
                    JSON.toJSONString(dynamicContext.getLogEvidence()),
                    JSON.toJSONString(dynamicContext.getTraceEvidence()),
                    JSON.toJSONString(dynamicContext.getRootCauseCandidates()),
                    JSON.toJSONString(reviewResult),
                    "SUPPLEMENTING",
                    "COLLECTING");

            collectSupplementalEvidence(requestParameter, dynamicContext, reviewResult.getRequiredTools());
            evidenceSignals = evidenceSignalExtractor.extract(
                    requestParameter,
                    dynamicContext.getMetricEvidence(),
                    dynamicContext.getLogEvidence(),
                    dynamicContext.getTraceEvidence());
            dynamicContext.setEvidenceSignals(evidenceSignals);
            workingMemoryService.refreshFromContext(requestParameter, dynamicContext);
            send(dynamicContext, OpsAnalyzeEventEntity.running("analysis", "evidence_signals_round_" + supplementRound, 5,
                    formatEvidenceSignals(evidenceSignals), requestParameter.getSessionId()));
            runbookMatches = collectRunbookPatterns(requestParameter, dynamicContext, evidenceSignals,
                    "refresh Runbook patterns after supplemental evidence collection");
            dynamicContext.setRunbookMatches(runbookMatches);
            dynamicContext.setRootCauseCandidates(List.of());
            workingMemoryService.refreshFromContext(requestParameter, dynamicContext);
            send(dynamicContext, OpsAnalyzeEventEntity.running("analysis", "evidence_chain_round_" + supplementRound, 5,
                    "Supplemented evidence has been collected. Evidence Reviewer Agent will re-evaluate root cause without pre-made hypotheses.",
                    requestParameter.getSessionId()));
            OpsEvidenceReviewResult finalReview = reviewAndPersist(requestParameter, dynamicContext, supplementRound, "REVIEWED");
            applyReviewerRootCause(requestParameter, dynamicContext, finalReview);
            send(dynamicContext, OpsAnalyzeEventEntity.running("agent", "evidence_reviewer_agent", 5,
                    buildReviewMessage(finalReview), requestParameter.getSessionId()));
        } else {
            applyReviewerRootCause(requestParameter, dynamicContext, reviewResult);
            send(dynamicContext, OpsAnalyzeEventEntity.running("agent", "evidence_reviewer_agent", 5,
                    buildReviewMessage(reviewResult), requestParameter.getSessionId()));
        }
        return router(requestParameter, dynamicContext);
    }

    @Override
    public StrategyHandler<IncidentCommandEntity, DefaultOpsAgentExecuteStrategyFactory.DynamicContext, String> get(
            IncidentCommandEntity requestParameter,
            DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext) throws Exception {
        return opsStep6RootCauseAnalysisNode;
    }

    private OpsEvidenceReviewResult reviewAndPersist(IncidentCommandEntity requestParameter,
                                                     DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext,
                                                     int round,
                                                     String stateStatus) {
        OpsEvidenceReviewResult reviewResult = evidenceReviewerService.review(
                requestParameter,
                dynamicContext,
                round,
                Math.max(1, maxRounds));
        dynamicContext.setEvidenceSemantics(reviewResult.getEvidenceSemantics());
        normalizeSupplementRequests(dynamicContext, reviewResult);
        dynamicContext.setValue("ops_evidence_review_result", reviewResult);
        workingMemoryService.refreshFromContext(requestParameter, dynamicContext);
        opsAgentStateService.updateReviewSnapshot(
                requestParameter.getDiagnosisId(),
                round,
                JSON.toJSONString(dynamicContext.getMetricEvidence()),
                JSON.toJSONString(dynamicContext.getLogEvidence()),
                JSON.toJSONString(dynamicContext.getTraceEvidence()),
                JSON.toJSONString(dynamicContext.getRootCauseCandidates()),
                JSON.toJSONString(reviewResult),
                reviewResult.getStatus(),
                stateStatus);
        persistReview(requestParameter, reviewResult);
        return reviewResult;
    }

    private void applyReviewerRootCause(IncidentCommandEntity requestParameter,
                                        DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext,
                                        OpsEvidenceReviewResult reviewResult) {
        if (reviewResult == null || isBlank(reviewResult.getRootCause())) {
            dynamicContext.setRootCauseCandidates(List.of(unresolvedCandidate(requestParameter, reviewResult)));
            workingMemoryService.refreshFromContext(requestParameter, dynamicContext);
            return;
        }
        RootCauseCandidateEntity candidate = RootCauseCandidateEntity.builder()
                .cause(reviewResult.getRootCause())
                .category(isBlank(reviewResult.getRootCauseCategory())
                        ? defaultRootCauseCategory(reviewResult)
                        : reviewResult.getRootCauseCategory())
                .confidence(reviewResult.getRootCauseConfidence() == null
                        ? reviewResult.getConfidenceScore()
                        : reviewResult.getRootCauseConfidence())
                .reasoning(reviewResult.getRootCauseRationale())
                .evidences(reviewerEvidenceItems(dynamicContext))
                .remediationSuggestions(reviewResult.getReportConstraints())
                .hypothesis(!"ROOT_CAUSE_CONFIRMED".equals(reviewResult.getConclusionType()))
                .origin("EVIDENCE_REVIEWER_AGENT")
                .missingEvidence(reviewResult.getMissingEvidence())
                .supportingSignals(dynamicContext.getEvidenceSignals() == null
                        ? List.of()
                        : dynamicContext.getEvidenceSignals().stream().map(EvidenceSignalEntity::getSignalId).toList())
                .build();
        dynamicContext.setRootCauseCandidates(List.of(candidate));
        workingMemoryService.refreshFromContext(requestParameter, dynamicContext);
    }

    private String defaultRootCauseCategory(OpsEvidenceReviewResult reviewResult) {
        if (reviewResult == null) {
            return "agent_reviewed";
        }
        if ("PROBABLE_ROOT_CAUSE".equals(reviewResult.getConclusionType())) {
            return "probable_root_cause";
        }
        if ("ROOT_CAUSE_CONFIRMED".equals(reviewResult.getConclusionType())) {
            return "confirmed_root_cause";
        }
        return "agent_reviewed";
    }

    private RootCauseCandidateEntity unresolvedCandidate(IncidentCommandEntity requestParameter,
                                                        OpsEvidenceReviewResult reviewResult) {
        return RootCauseCandidateEntity.builder()
                .cause(isInvestigationCompleteUnresolved(reviewResult)
                        ? "Investigation complete; specific root cause is not confirmed by current evidence"
                        : "Evidence Reviewer did not finalize a root cause")
                .category(isInvestigationCompleteUnresolved(reviewResult)
                        ? "investigation_complete_root_cause_unresolved"
                        : "insufficient_evidence")
                .confidence(reviewResult == null || reviewResult.getConfidenceScore() == null ? 0 : reviewResult.getConfidenceScore())
                .reasoning(reviewResult == null ? "Review result is empty." : reviewResult.getRationale())
                .evidences(List.of(EvidenceItemEntity.builder()
                        .source("reviewer")
                        .category("agent_review")
                        .title("Root cause unresolved")
                        .detail(requestParameter == null ? "" : requestParameter.getProblem())
                        .confidence(0)
                        .build()))
                .remediationSuggestions(reviewResult == null ? List.of() : reviewResult.getReportConstraints())
                .hypothesis(true)
                .origin("EVIDENCE_REVIEWER_AGENT")
                .missingEvidence(reviewResult == null ? List.of("Evidence review result is empty.") : reviewResult.getMissingEvidence())
                .supportingSignals(List.of())
                .build();
    }

    private boolean isInvestigationCompleteUnresolved(OpsEvidenceReviewResult reviewResult) {
        return reviewResult != null
                && "SUFFICIENT".equals(reviewResult.getStatus())
                && "INVESTIGATION_COMPLETE_ROOT_CAUSE_UNRESOLVED".equals(reviewResult.getConclusionType());
    }

    private List<EvidenceItemEntity> reviewerEvidenceItems(DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext) {
        List<EvidenceItemEntity> items = new java.util.ArrayList<>();
        if (dynamicContext.getEvidenceSignals() != null) {
            for (EvidenceSignalEntity signal : dynamicContext.getEvidenceSignals()) {
                EvidenceSemanticEntity semantic = findSemantic(dynamicContext.getEvidenceSemantics(), signal);
                items.add(EvidenceItemEntity.builder()
                        .source(signal.getSource())
                        .category(signal.getEvidenceType())
                        .title(signal.getName() + " [" + signal.getStatus() + "]"
                                + (semantic == null ? "" : " => " + semantic.getSemanticType()))
                        .detail(signal.getSummary()
                                + (semantic == null || isBlank(semantic.getReasoning()) ? "" : "\nSemantic reasoning: " + semantic.getReasoning()))
                        .confidence(semantic == null || semantic.getEvidenceStrength() == null
                                ? ("ANOMALY".equals(signal.getStatus()) ? 70 : 45)
                                : semantic.getEvidenceStrength())
                        .build());
            }
        }
        if (dynamicContext.getRunbookMatches() != null) {
            for (RunbookMatchEntity match : dynamicContext.getRunbookMatches()) {
                items.add(EvidenceItemEntity.builder()
                        .source("runbook")
                        .category(match.getCategory())
                        .title(match.getTitle())
                        .detail(match.getSummary())
                        .confidence(match.getScore())
                        .build());
            }
        }
        return items;
    }

    private EvidenceSemanticEntity findSemantic(List<EvidenceSemanticEntity> semantics, EvidenceSignalEntity signal) {
        if (semantics == null || semantics.isEmpty() || signal == null) {
            return null;
        }
        for (EvidenceSemanticEntity semantic : semantics) {
            if (!isBlank(semantic.getSignalId()) && semantic.getSignalId().equals(signal.getSignalId())) {
                return semantic;
            }
        }
        for (EvidenceSemanticEntity semantic : semantics) {
            if (!isBlank(semantic.getSignalName()) && semantic.getSignalName().equals(signal.getName())
                    && !isBlank(semantic.getSource()) && semantic.getSource().equals(signal.getSource())) {
                return semantic;
            }
        }
        return null;
    }

    private boolean needsSupplement(OpsEvidenceReviewResult reviewResult) {
        return reviewResult != null
                && Boolean.FALSE.equals(reviewResult.getSufficient())
                && "NEED_MORE_EVIDENCE".equals(reviewResult.getStatus())
                && reviewResult.getRound() != null
                && reviewResult.getRound() < Math.max(1, maxRounds)
                && reviewResult.getRequiredTools() != null
                && !reviewResult.getRequiredTools().isEmpty();
    }

    private void normalizeSupplementRequests(DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext,
                                             OpsEvidenceReviewResult reviewResult) {
        if (dynamicContext == null || reviewResult == null || reviewResult.getRequiredTools() == null
                || reviewResult.getRequiredTools().isEmpty()) {
            return;
        }
        List<String> collectableTools = new ArrayList<>();
        List<String> suppressedTools = new ArrayList<>();
        for (String toolName : reviewResult.getRequiredTools()) {
            if (canActuallySupplement(dynamicContext, toolName)) {
                collectableTools.add(toolName);
            } else {
                suppressedTools.add(toolName);
            }
        }
        if (suppressedTools.isEmpty()) {
            return;
        }
        reviewResult.setRequiredTools(collectableTools);
        List<String> confirmedFacts = new ArrayList<>();
        if (reviewResult.getConfirmedFacts() != null) {
            confirmedFacts.addAll(reviewResult.getConfirmedFacts());
        }
        confirmedFacts.add("Supplement request suppressed because already collected sources returned normal/empty evidence, not missing evidence: " + suppressedTools);
        reviewResult.setConfirmedFacts(confirmedFacts);
        List<String> constraints = new ArrayList<>();
        if (reviewResult.getReportConstraints() != null) {
            constraints.addAll(reviewResult.getReportConstraints());
        }
        constraints.add("Treat successfully collected NO_ANOMALY/OK sources as negative evidence; do not re-collect the same source only because no abnormal records were found.");
        reviewResult.setReportConstraints(constraints);
        if (collectableTools.isEmpty() && "NEED_MORE_EVIDENCE".equals(reviewResult.getStatus())) {
            reviewResult.setStatus("SUFFICIENT");
            reviewResult.setSufficient(true);
            reviewResult.setConclusionType(isBlank(reviewResult.getRootCause())
                    ? "INVESTIGATION_COMPLETE_ROOT_CAUSE_UNRESOLVED"
                    : "PROBABLE_ROOT_CAUSE");
            reviewResult.setRationale(reviewResult.getRationale()
                    + "; supplementGate=SUPPRESSED_ALREADY_COLLECTED_NORMAL_SOURCES, convertedConclusionType="
                    + reviewResult.getConclusionType() + ", suppressedTools=" + suppressedTools);
        }
    }

    private boolean canActuallySupplement(DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext,
                                          String toolName) {
        if ("query_prometheus".equals(toolName)) {
            return !available(dynamicContext.getMetricEvidence());
        }
        if ("query_elasticsearch".equals(toolName)) {
            return !available(dynamicContext.getLogEvidence());
        }
        if ("query_skywalking_trace".equals(toolName)) {
            return !available(dynamicContext.getTraceEvidence());
        }
        if ("query_runbook".equals(toolName)) {
            return dynamicContext.getRunbookMatches() == null;
        }
        return false;
    }

    private void persistReview(IncidentCommandEntity requestParameter, OpsEvidenceReviewResult reviewResult) {
        if (requestParameter == null || reviewResult == null) {
            return;
        }
        OpsInvestigationPlan plan = opsAgentRepository.queryLatestPlanByDiagnosisId(requestParameter.getDiagnosisId());
        LocalDateTime now = LocalDateTime.now();
        opsAgentRepository.saveAgentReview(OpsAgentReview.builder()
                .reviewId("review-" + UUID.randomUUID())
                .diagnosisId(requestParameter.getDiagnosisId())
                .stateId(plan == null ? null : plan.getStateId())
                .planId(plan == null ? null : plan.getPlanId())
                .round(reviewResult.getRound())
                .reviewStatus(reviewResult.getStatus())
                .sufficient(reviewResult.getSufficient())
                .confidence(reviewResult.getConfidenceScore())
                .confirmedFactsJson(JSON.toJSONString(reviewResult.getConfirmedFacts()))
                .weakEvidenceJson(JSON.toJSONString(reviewResult.getWeakEvidence()))
                .missingEvidenceJson(JSON.toJSONString(reviewResult.getMissingEvidence()))
                .nextActionsJson(JSON.toJSONString(reviewResult.getRequiredTools()))
                .reportConstraintsJson(JSON.toJSONString(reviewResult.getReportConstraints()))
                .stopReason(resolveStopReason(reviewResult))
                .reviewerType(resolveReviewerType(reviewResult))
                .reviewJson(JSON.toJSONString(reviewResult))
                .createTime(now)
                .updateTime(now)
                .build());
    }

    private String resolveStopReason(OpsEvidenceReviewResult reviewResult) {
        if (reviewResult == null) {
            return "review result is empty";
        }
        if (Boolean.TRUE.equals(reviewResult.getSufficient())) {
            if ("PROBABLE_ROOT_CAUSE".equals(reviewResult.getConclusionType())) {
                return "investigation complete with probable root cause";
            }
            if ("INVESTIGATION_COMPLETE_ROOT_CAUSE_UNRESOLVED".equals(reviewResult.getConclusionType())) {
                return "investigation complete but specific root cause is unresolved";
            }
            return "evidence sufficient for root cause confirmation";
        }
        if ("NEED_MORE_EVIDENCE".equals(reviewResult.getStatus())) {
            return "supplementary evidence required";
        }
        if ("INSUFFICIENT_FINAL".equals(reviewResult.getStatus())) {
            return "max review round reached or evidence remains insufficient";
        }
        return reviewResult.getRationale();
    }

    private String resolveReviewerType(OpsEvidenceReviewResult reviewResult) {
        String rationale = reviewResult == null ? "" : reviewResult.getRationale();
        if (rationale != null && rationale.contains("chatAgent=CHAT_AGENT")) {
            return "CHAT_AGENT";
        }
        if (rationale != null && rationale.contains("chatAgent=RULE_BASED_FALLBACK")) {
            return "RULE_BASED_FALLBACK";
        }
        return "RULE_BASED";
    }

    private void collectSupplementalEvidence(IncidentCommandEntity requestParameter,
                                             DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext,
                                             List<String> requiredTools) {
        if (requiredTools == null || requiredTools.isEmpty()) {
            return;
        }
        for (String toolName : requiredTools) {
            if ("query_prometheus".equals(toolName) && !available(dynamicContext.getMetricEvidence())) {
                collectMetricEvidence(requestParameter, dynamicContext);
            } else if ("query_elasticsearch".equals(toolName) && !available(dynamicContext.getLogEvidence())) {
                collectLogEvidence(requestParameter, dynamicContext);
            } else if ("query_skywalking_trace".equals(toolName) && !available(dynamicContext.getTraceEvidence())) {
                collectTraceEvidence(requestParameter, dynamicContext);
            } else if ("query_runbook".equals(toolName)
                    && (dynamicContext.getRunbookMatches() == null || dynamicContext.getRunbookMatches().isEmpty())) {
                List<EvidenceSignalEntity> signals = dynamicContext.getEvidenceSignals();
                if (signals == null) {
                    signals = evidenceSignalExtractor.extract(requestParameter,
                            dynamicContext.getMetricEvidence(),
                            dynamicContext.getLogEvidence(),
                            dynamicContext.getTraceEvidence());
                    dynamicContext.setEvidenceSignals(signals);
                }
                collectRunbookPatterns(requestParameter, dynamicContext, signals,
                        "supplement Runbook patterns requested by Evidence Reviewer");
            }
        }
    }

    private List<RunbookMatchEntity> collectRunbookPatterns(IncidentCommandEntity requestParameter,
                                                            DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext,
                                                            List<EvidenceSignalEntity> evidenceSignals,
                                                            String intent) {
        List<RunbookMatchEntity> existing = dynamicContext.getRunbookMatches();
        if (existing != null && !existing.isEmpty() && !"refresh Runbook patterns after supplemental evidence collection".equals(intent)) {
            return existing;
        }
        if (!planExecutionService.shouldExecute(dynamicContext, "query_runbook")) {
            planExecutionService.recordDecision(requestParameter, dynamicContext, "query_runbook", "Runbook Agent",
                    "SKIPPED", "tool not selected by investigation plan before evidence review");
            return existing == null ? List.of() : existing;
        }
        OpsToolGovernanceDecision governanceDecision = requestToolAccess(requestParameter, dynamicContext,
                "query_runbook", "Runbook Agent", intent);
        if (!governanceDecision.isAllowed()) {
            return existing == null ? List.of() : existing;
        }
        List<RunbookMatchEntity> matches = runbookGateway.searchByEvidenceSignals(requestParameter, evidenceSignals, 4);
        opsAgentStateService.updateRunbookEvidence(requestParameter.getDiagnosisId(), JSON.toJSONString(matches));
        planExecutionService.recordDecision(requestParameter, dynamicContext, "query_runbook", "Runbook Agent",
                "EXECUTED", "Runbook patterns retrieved from neutral evidence signals.");
        send(dynamicContext, OpsAnalyzeEventEntity.running("rag", "runbook_pattern", 5,
                formatRunbookMatches(matches), requestParameter.getSessionId()));
        return matches;
    }

    private void collectMetricEvidence(IncidentCommandEntity requestParameter,
                                       DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext) {
        try {
            OpsToolGovernanceDecision governanceDecision = requestToolAccess(requestParameter, dynamicContext,
                    "query_prometheus", "Metrics Agent", "supplement metrics requested by Evidence Reviewer");
            if (!governanceDecision.isAllowed()) {
                return;
            }
            MetricEvidenceEntity evidence = metricGateway.queryMetrics(requestParameter);
            dynamicContext.setMetricEvidence(evidence);
            planExecutionService.recordDecision(requestParameter, dynamicContext, "query_prometheus", "Metrics Agent",
                    "SUPPLEMENTED", "Evidence Reviewer requested missing metrics evidence.");
            send(dynamicContext, OpsAnalyzeEventEntity.running("metric", "prometheus_reflection", 5,
                    buildMetricMessage(evidence), requestParameter.getSessionId()));
        } catch (Exception e) {
            planExecutionService.recordDecision(requestParameter, dynamicContext, "query_prometheus", "Metrics Agent",
                    "FAILED", "Supplemental metrics collection failed: " + e.getMessage());
            log.warn("Supplemental Prometheus evidence failed. diagnosisId={}", requestParameter.getDiagnosisId(), e);
        }
    }

    private void collectLogEvidence(IncidentCommandEntity requestParameter,
                                    DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext) {
        try {
            OpsToolGovernanceDecision governanceDecision = requestToolAccess(requestParameter, dynamicContext,
                    "query_elasticsearch", "Logs Agent", "supplement logs requested by Evidence Reviewer");
            if (!governanceDecision.isAllowed()) {
                return;
            }
            LogEvidenceEntity evidence = logGateway.queryLogs(requestParameter);
            dynamicContext.setLogEvidence(evidence);
            planExecutionService.recordDecision(requestParameter, dynamicContext, "query_elasticsearch", "Logs Agent",
                    "SUPPLEMENTED", "Evidence Reviewer requested missing log evidence.");
            send(dynamicContext, OpsAnalyzeEventEntity.running("log", "elk_reflection", 5,
                    buildLogMessage(evidence), requestParameter.getSessionId()));
        } catch (Exception e) {
            planExecutionService.recordDecision(requestParameter, dynamicContext, "query_elasticsearch", "Logs Agent",
                    "FAILED", "Supplemental log collection failed: " + e.getMessage());
            log.warn("Supplemental ELK evidence failed. diagnosisId={}", requestParameter.getDiagnosisId(), e);
        }
    }

    private void collectTraceEvidence(IncidentCommandEntity requestParameter,
                                      DefaultOpsAgentExecuteStrategyFactory.DynamicContext dynamicContext) {
        try {
            OpsToolGovernanceDecision governanceDecision = requestToolAccess(requestParameter, dynamicContext,
                    "query_skywalking_trace", "Trace Agent", "supplement traces requested by Evidence Reviewer");
            if (!governanceDecision.isAllowed()) {
                return;
            }
            TraceEvidenceEntity evidence = traceGateway.queryTrace(requestParameter);
            dynamicContext.setTraceEvidence(evidence);
            planExecutionService.recordDecision(requestParameter, dynamicContext, "query_skywalking_trace", "Trace Agent",
                    "SUPPLEMENTED", "Evidence Reviewer requested missing trace evidence.");
            send(dynamicContext, OpsAnalyzeEventEntity.running("trace", "skywalking_reflection", 5,
                    buildTraceMessage(evidence), requestParameter.getSessionId()));
        } catch (Exception e) {
            planExecutionService.recordDecision(requestParameter, dynamicContext, "query_skywalking_trace", "Trace Agent",
                    "FAILED", "Supplemental trace collection failed: " + e.getMessage());
            log.warn("Supplemental SkyWalking evidence failed. diagnosisId={}", requestParameter.getDiagnosisId(), e);
        }
    }

    private String buildReviewMessage(OpsEvidenceReviewResult reviewResult) {
        if (reviewResult == null) {
            return "Evidence Reviewer Agent returned no review result.";
        }
        return "Evidence Reviewer Agent status=" + reviewResult.getStatus()
                + ", conclusionType=" + reviewResult.getConclusionType()
                + ", round=" + reviewResult.getRound()
                + ", confidence=" + reviewResult.getConfidenceScore()
                + "\nRoot cause:\n" + blankToDefault(reviewResult.getRootCause(), "- none")
                + "\nConfirmed facts:\n" + join(reviewResult.getConfirmedFacts())
                + "\nWeak evidence:\n" + join(reviewResult.getWeakEvidence())
                + "\nMissing evidence:\n" + join(reviewResult.getMissingEvidence())
                + "\nRequired tools:\n" + join(reviewResult.getRequiredTools())
                + "\nReport constraints:\n" + join(reviewResult.getReportConstraints())
                + "\nRationale: " + reviewResult.getRationale();
    }

    private String formatEvidenceSignals(List<EvidenceSignalEntity> evidenceSignals) {
        if (evidenceSignals == null || evidenceSignals.isEmpty()) {
            return "No neutral evidence signals extracted.";
        }
        StringBuilder builder = new StringBuilder("Neutral evidence signals extracted. These are observations, not root-cause conclusions.\n");
        for (EvidenceSignalEntity signal : evidenceSignals) {
            builder.append("- ")
                    .append(signal.getSource()).append("/")
                    .append(signal.getEvidenceType()).append(" ")
                    .append(signal.getName()).append(" [")
                    .append(signal.getStatus()).append("] ")
                    .append(signal.getSummary()).append("\n");
        }
        return builder.toString();
    }

    private boolean available(MetricEvidenceEntity evidence) {
        return evidence != null && evidence.isAvailable();
    }

    private boolean available(LogEvidenceEntity evidence) {
        return evidence != null && evidence.isAvailable();
    }

    private boolean available(TraceEvidenceEntity evidence) {
        return evidence != null && evidence.isAvailable();
    }

    private String join(List<String> items) {
        if (items == null || items.isEmpty()) {
            return "- none";
        }
        StringBuilder builder = new StringBuilder();
        for (String item : items) {
            builder.append("- ").append(item).append("\n");
        }
        return builder.toString();
    }

    private boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }

    private String blankToDefault(String value, String defaultValue) {
        return isBlank(value) ? defaultValue : value;
    }

}


